apiVersion: v1
kind: Pod
metadata:
  name: flask-redis
spec:
  containers:
  - name: flask
    image: localhost/flask:app
    ports:
    - containerPort: 5000
      hostPort: 5000
    volumeMounts:
    - mountPath: /app
      name: flask-redis-vol
  - name: redis
    image: docker.io/redislabs/redismod
    ports:
    - containerPort: 6379
      hostPort: 6379
  volumes:
  - hostPath:
      path: flask  # folder for flask/app.py
      type: Directory
    name: flask-redis-vol
