FROM docker.io/python:3.10-slim-buster

RUN apt-get update \
      && apt-get install --no-install-recommends -y curl \
    && apt-get clean && rm -rf /var/lib/apt/lists/*
    
COPY . /app
WORKDIR /app
RUN pip install -r requirements.txt

CMD ["gunicorn", "--reload", "-b", "0.0.0.0:5000", "app:app"]
